### ISSUE TITLE
Lack of documentation about where K8sBearerToken is from

### ISSUE THREAD

**Issue by JohnNiang** [LinuxSuRen/kubesphere#6]
Please see the bellow line:

https://github.com/LinuxSuRen/kubesphere/blob/bc6b9664cc38ae8ecacbee33b0d1fbf06601a7ef/pkg/simple/client/devops/jenkins/options.go#L35

There is no documentation to describe where we can get K8sBearerToken appropriately. Anyone could help me to find it out?

**Comment by LinuxSuRen** [comment]
It does not have the document because we don't need it. It's an inner field as I described in the comment.

**Comment by JohnNiang** [comment]
Thank @LinuxSuRen for explanation.
